packages:
  - 'packages/*'
  - playground
  - docs

catalog:
  '@antfu/eslint-config': ^5.0.0
  '@clack/prompts': ^0.11.0
  '@iconify/json': ^2.2.365
  '@rollup/plugin-json': ^6.1.0
  '@shikijs/vitepress-twoslash': ^3.9.2
  '@tsconfig/node20': ^20.1.3
  '@types/node': ^22.15.2
  '@vitejs/plugin-vue': ^6.0.1
  '@vitejs/plugin-vue-jsx': ^5.0.1
  '@vue/tsconfig': ^0.7.0
  ant-design-vue: ^4.2.6
  eslint: ^9.32.0
  eslint-plugin-format: ^1.0.1
  gray-matter: ^4.0.3
  jsdom: ^26.1.0
  lint-staged: ^16.1.2
  npm-run-all2: ^8.0.4
  picocolors: ^1.1.1
  pinia: ^3.0.3
  prettier: ^3.5.3
  simple-git-hooks: ^2.13.0
  tinyglobby: ^0.2.14
  tsdown: ^0.16.6
  typescript: ^5.8.3
  unocss: ^66.4.0
  unplugin-vue-router: ^0.14.0
  vite: ^7.0.6
  vite-plugin-vue-devtools: ^8.0.0
  vitepress: ^2.0.0-alpha.9
  vitest: ^3.2.4
  vue: ^3.5.13
  vue-router: ^4.5.1
  vue-tsc: ^3.0.4

shamefullyHoist: true
shellEmulator: true
sideEffectsCache: false
strictPeerDependencies: false
