/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/async-component/': RouteRecordInfo<'/async-component/', '/async-component', Record<never, never>, Record<never, never>>,
    '/elementPlus/': RouteRecordInfo<'/elementPlus/', '/elementPlus', Record<never, never>, Record<never, never>>,
    '/fetch/': RouteRecordInfo<'/fetch/', '/fetch', Record<never, never>, Record<never, never>>,
    '/watermark/': RouteRecordInfo<'/watermark/', '/watermark', Record<never, never>, Record<never, never>>,
  }
}
